# Generated by Django 4.2.7 on 2023-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='data_av',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Avaliação'),
        ),
    ]
