# Generated by Django 4.2.7 on 2023-12-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('checklist', '0005_avaliacao_remove_resposta_data_av_resposta_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Loja'),
        ),
    ]
