# Generated by Django 4.2.7 on 2023-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_avaliacao_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
