# Generated by Django 4.2.7 on 2023-12-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_remove_resposta_obs_avaliacao_obs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='userchecklist',
            options={'verbose_name': 'Usuário Checklist', 'verbose_name_plural': 'Usuários Checklist'},
        ),
        migrations.AlterField(
            model_name='resposta',
            name='avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_set', to='checklist.avaliacao'),
        ),
    ]
