# Generated by Django 4.2.7 on 2023-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_alter_avaliacao_options_alter_questao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='media',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Média'),
        ),
    ]
