# Generated by Django 4.2.7 on 2023-12-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_subtopico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopico',
            name='name',
        ),
    ]
