# Generated by Django 4.2.7 on 2023-12-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_remove_subtopico_questao_questao_subtopico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='subtopico',
        ),
        migrations.DeleteModel(
            name='Subtopico',
        ),
    ]
