# Generated by Django 4.2.7 on 2023-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_tipoavaliacao_alter_questao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='media_geral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Média'),
        ),
    ]
