# Generated by Django 4.2.7 on 2023-12-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0017_alter_avaliacao_media_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopico',
            name='nome',
            field=models.CharField(blank=True, choices=[('Separação', 'Separação'), ('Operação de loja', 'Operação de loja'), ('Processos', 'Processos'), ('Sistema', 'Sistema')], max_length=255, null=True),
        ),
    ]
