# Generated by Django 4.2.7 on 2023-12-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_alter_subtopico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopico',
            name='nome',
            field=models.CharField(blank=True, choices=[('Separação', 'Separação'), ('Operação de loja', 'Operação de loja'), ('Processos', 'Processos'), ('Equipamentos', 'Equipamentos')], max_length=255, null=True),
        ),
    ]
